[[redirects]]
  from = "/p/*"
  to = ":splat"
  status = 200
  headers = {Access-Control-Allow-Origin = "https://bell.harker.org"}
[[redirects]]
  from = "/pgtm/*"
  to = "https://www.googletagmanager.com/gtm.js:splat"
  status = 200
  headers = {Access-Control-Allow-Origin = "https://bell.harker.org"}
[[redirects]]
  from = "/submitevent"
  to = "https://docs.google.com/forms/d/e/1FAIpQLSeWUzPcr079_ZhXHlRcwKwsoMjJL5O_ZsWVulzMjqVxHOb7Fg/viewform"
  status = 302
[[redirects]]
  from = "/docs/*"
  to = "https://harker-bell-docs.netlify.com/:splat"
  status = 200
[[redirects]]
  from = "/admin/*"
  to = "https://harker-bell-admin.netlify.com/:splat"
  status = 200
[[redirects]]
  from = "/api/*"
  to = "https://bell-dev.harkerdev.com/api/:splat"
  status = 200
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
